import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTripLog } from '../hooks/useTripLog'
import CatchForm from '../components/CatchForm'
import type { Catch } from '../types'

function todayString(): string {
  return new Date().toISOString().split('T')[0]
}

export default function NewTrip() {
  const navigate = useNavigate()
  const { saveTrip } = useTripLog()

  const [date, setDate] = useState(todayString())
  const [lake, setLake] = useState('')
  const [notes, setNotes] = useState('')
  const [catches, setCatches] = useState<Catch[]>([])
  const [showCatchForm, setShowCatchForm] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saveError, setSaveError] = useState<string | null>(null)

  function addCatch(catch_: Catch) {
    setCatches(prev => [...prev, catch_])
    setShowCatchForm(false)
  }

  function removeCatch(id: string) {
    setCatches(prev => prev.filter(c => c.id !== id))
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    if (!lake.trim()) return

    setSaving(true)
    setSaveError(null)

    try {
      await saveTrip({
        id: '',           // generated by DB — ignored in the insert
        createdAt: '',    // generated by DB — ignored in the insert
        date,
        lake: lake.trim(),
        notes: notes.trim() || undefined,
        catches,
      })
      navigate('/log')
    } catch (err) {
      setSaveError(err instanceof Error ? err.message : 'Failed to save trip')
      setSaving(false)
    }
  }

  const inputClass =
    'w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-sm text-gray-800 placeholder-gray-400 shadow-sm focus:outline-none focus:ring-2 focus:ring-teal-600 focus:border-transparent'

  return (
    <div className="pt-6 pb-8">
      <div className="px-4 mb-5">
        <h1 className="text-2xl font-bold text-gray-900">New Trip</h1>
      </div>

      <form onSubmit={handleSubmit} className="px-4 space-y-4">
        {/* Trip details */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 space-y-4">
          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Trip Details</p>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Date</label>
            <input
              type="date"
              value={date}
              onChange={e => setDate(e.target.value)}
              className={inputClass}
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Lake / Location *</label>
            <input
              type="text"
              value={lake}
              onChange={e => setLake(e.target.value)}
              placeholder="e.g. Lake Butler, FL"
              className={inputClass}
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Notes</label>
            <textarea
              value={notes}
              onChange={e => setNotes(e.target.value)}
              placeholder="Conditions, structure, anything worth remembering…"
              rows={3}
              className={inputClass + ' resize-none'}
            />
          </div>
        </div>

        {/* Catches */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 space-y-3">
          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Catches</p>

          {catches.length === 0 && !showCatchForm && (
            <p className="text-sm text-gray-400">No catches logged yet.</p>
          )}

          {catches.map(c => (
            <div
              key={c.id}
              className="flex items-start justify-between gap-2 bg-gray-50 rounded-xl px-3 py-3 border border-gray-100"
            >
              <div className="min-w-0">
                <p className="text-sm font-semibold text-gray-800">{c.species}</p>
                <p className="text-xs text-gray-500 mt-0.5">{c.bait}</p>
                {(c.weight || c.length || c.timeCaught) && (
                  <p className="text-xs text-gray-400 mt-0.5">
                    {[c.weight, c.length, c.timeCaught].filter(Boolean).join(' · ')}
                  </p>
                )}
              </div>
              <button
                type="button"
                onClick={() => removeCatch(c.id)}
                className="text-gray-300 hover:text-red-400 transition-colors flex-shrink-0 text-lg leading-none"
                aria-label="Remove catch"
              >
                ×
              </button>
            </div>
          ))}

          {showCatchForm ? (
            <CatchForm onAdd={addCatch} onCancel={() => setShowCatchForm(false)} />
          ) : (
            <button
              type="button"
              onClick={() => setShowCatchForm(true)}
              className="w-full py-2.5 rounded-xl border border-dashed border-teal-300 text-sm font-medium text-teal-600 hover:bg-teal-50 transition-colors"
            >
              + Add Catch
            </button>
          )}
        </div>

        {saveError && (
          <div className="bg-red-50 border border-red-100 rounded-xl px-4 py-3">
            <p className="text-sm text-red-700">{saveError}</p>
          </div>
        )}

        {/* Save */}
        <button
          type="submit"
          disabled={!lake.trim() || saving}
          className="w-full py-3.5 bg-teal-600 hover:bg-teal-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold rounded-xl shadow-sm transition-colors"
        >
          {saving ? 'Saving…' : 'Save Trip'}
        </button>
      </form>
    </div>
  )
}
